#!/bin/bash

# Default $SUBDIR to CITS4230
if [ "$SUBDIR" == "" ]; then
	SUBDIR="CITS4230"
fi
# If a Student ID is not provided then ask for it on stdin
if [ "$ID" == "" ]; then
	echo -n "What's your student ID? "
	read ID
fi
# If the CLEAR flag is set to 1 then clear the remote directory $SUBDIR in WWW
if [ "$CLEAR" == "1" ]; then
	echo "Will clear before copying."
	RSYNC_EXTRA+=" --del"
fi
# Copy the files in WWW to remote WWW/$SUBDIR
echo "Copying..."
rsync$RSYNC_EXTRA -a -e ssh WWW/ "$ID@uggp.csse.uwa.edu.au:~/WWW/$SUBDIR/"
